Isu0034 when running up server default to production
nherriot/noisy-atom-portal pull request #36
Opened 2022-02-20 19:54 UTC by nherriot

This closes issue #34 

This changes how the system starts. We now no longer require a string of dev machines that are scanned to know when to start in dev mode or production mode. The system looks at an environment variable. This is used to start in **dev** or **prod**. To test this out do:

## Test 1
Check the file /noisyatom/config/.env has an attribute called ENVIRONMENT set as dev:

```
ENVIRONMENT=dev
```
Run the server and check for the lines:

```
***** WARNING! This is a non-production build *****
***** Environment is set as: dev *****
```

## Test 2
Change the environment variables to **prod**

```
ENVIRONMENT=prod
```
Run the server and check for the lines:

```
***** INFORMATION: PRODUCTION BUILD DEPLOYMENT *****
***** Environment is set as: prod *****
```

## Test 3
Remove the environment variable for the .env file.

Run the server and check for the lines:

```
***** WARNING! This is a non-production build *****
***** Environment is set as: dev *****
```

2022-06-01 16:19 UTC, tine3700 requested changes

2022-06-01 16:19 UTC, tine3700 commented on documentation/README.md
>  /> sudo pip install virtualenvwrapper
The commands for setting up the virtual env has worked before. What is the reason this is changing now?

2022-06-03 10:17 UTC, nherriot commented on documentation/README.md
>  /> sudo pip install virtualenvwrapper
Good catch. Thank you. :-)

2022-06-03 11:07 UTC, tine3700 approved these changes

2022-06-03 11:07 UTC, merged