35 isu0035 create a plain dockerfile and docker compose to just bring up a vanilla linux machine with python installed and setup
nherriot/noisy-atom-portal pull request #53
Opened 2022-06-09 16:43 UTC by tine3700

This fixes ISU0035 building a Dockerfile using the docker image Python slim 3.8 and using a docker-compose file to build the development server.

2022-06-10 17:56 UTC, nherriot commented on documentation/README.md
> +```
You need to remove '''. As this all looks like a code block.

2022-06-10 18:10 UTC, nherriot requested changes
I noticed too many ''' in the comments for readme files.

The app works from docker compose! :-) Fantastic. And the readme is now the standard we all have to meet! :-( ...

Only thing that is needed is the Dockerfile and docker-compose.yml need to be in the directory above. As they are both running in the container. They should not be inside the container.


```docker exec -it noisyatom_web_1 bash
root@cdc5ddd7f66c:/app# ls -l
total 320
-rw-rw-r-- 1 1000 1000    716 Jun 10 17:57 Dockerfile
-rw-rw-r-- 1 1000 1000     24 May 26 18:43 __init__.py
drwxrwxr-x 2 1000 1000   4096 May 26 19:13 __pycache__
drwxrwxr-x 5 1000 1000   4096 May 26 18:54 account
drwxrwxr-x 8 1000 1000   4096 May 30 21:39 blogs
drwxrwxr-x 4 1000 1000   4096 May 30 21:39 catalog
drwxrwxr-x 5 1000 1000   4096 May 30 21:33 cms
drwxrwxr-x 3 1000 1000   4096 Jun  9 10:29 config
-rw-rw-r-- 1 1000 1000    510 Jun 10 17:57 docker-compose.yml
drwxrwxr-x 5 1000 1000   4096 May 30 21:39 ee_test
-rwxrwxr-x 1 1000 1000    804 May 26 18:43 manage.py
-rw-rw-r-- 1 1000 1000 262144 May 30 21:33 na_db
drwxrwxr-x 4 1000 1000   4096 May 30 21:33 qrcode
-rw-rw-r-- 1 1000 1000    324 Jun  9 10:29 requirements.txt
drwxrwxr-x 6 1000 1000   4096 May 26 18:43 static
drwxrwxr-x 3 1000 1000   4096 May 26 18:43 templates
drwxrwxr-x 3 1000 1000   4096 May 26 18:54 utils
```

2022-06-12 18:10 UTC, tine3700 commented
The Dockerfile and docker-compose.yml have been moved up one directory.

2022-06-14 13:27 UTC, nherriot approved these changes
LGTM

2022-06-14 13:27 UTC, merged